version: "2"
linters:
  enable:
    - dogsled
    - funlen
    - gochecknoinits
    - gocritic
    - gocyclo
    - godox
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
  settings:
    funlen:
      lines: 128
      statements: 64
    goconst:
      min-len: 12
    govet:
      enable-all: true
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - gosec
        text: "G115:"
      - linters:
          - gosec
        text: "G602:"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
